dataconfig:
  db-url: jdbc:oracle:thin:@211.238.142.200:1521:xe #localhost
  db-username: cteam01 #user01
  db-password: a1234   
  rememberme-key: hayden
  mail-username: teamsync97@gmail.com
  mail-password: knjxxoxiytxzqdpc
  groq-api-key: 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